version: "3"
services:
  app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "python3 /var/code/backend/manage.py migrate && python3 /var/code/backend/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/var/code
    ports:
      - "8001:8000"
    depends_on:
      - db
    networks:
      - db_network
  db:
    image: mysql:8
    volumes:
     - "./db/data:/var/lib/mysql"
#     - "./mysql/conf/my.cnf:/etc/mysql/my.cnf"
    command: "mysqld --user=root --explicit_defaults_for_timestamp --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci --default-authentication-plugin=mysql_native_password"
    ports:
      - "3307:3306"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=lagoudb_docker
    networks:
      - db_network
networks:
  db_network:
    driver: bridge
